<?
$tomb[version]='2280a';
$tomb[useadmin]='1';
$tomb[user]='admin';
$tomb[pass]='123456';
$tomb[library]='./lib/library2.php';
$tomb[database]='./data.php';
$tomb[max_view]='15';
$tomb[max_total]='50';
$tomb[max_str]='300';
$tomb[refresh_time]='30';
$tomb[smiles]='1';
$tomb[show_url]='1';
$tomb[show_date]='1';
$tomb[show_codes]='1';
$tomb[skin]='original';
$tomb[max_word]='50';
$tomb[timezone]='';
?>
